version: '3'

services:
  mysql:
    build: ./project/backend/db
    container_name: some-mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 30s
      retries: 5

  web:
    build:
      context: ./project/backend
      dockerfile: Dockerfile
    ports:
      - "8880:8880"
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

volumes:
  mysql_data:

