apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app-deployment
  template:
    metadata:
      labels:
        app: backend-app-deployment
    spec:
      containers:
      - name: backend-app-deployment
        image: backend-app:latest
        ports:
        - containerPort: 3030
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: test
        - name: MYSQL_PORT
          value: "3306"
        - name: PORT
          value: "3030"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-deployment-service
spec:
  selector:
    app: backend-app-deployment
  ports:
  - protocol: TCP
    port: 3030
    targetPort: 3030
  type: NodePort