apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-host-path
  labels:
    app: nginx-host-path
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-host-path
  template:
    metadata:
      labels:
        app: nginx-host-path
    spec:
      volumes:
      - name: nginx-host-path-volume
        hostPath:
          path: /mnt/hostPath/  # Specify the path on the host machine
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80
          name: "http-server"
        volumeMounts:
        - name: nginx-host-path-volume
          mountPath: /usr/share/nginx/html # Mount path inside the container

