apiVersion: v1
kind: Service
metadata:
  name: kubernetes-bootcamp-service
spec:
  type: NodePort
  selector:
    app: kubernetes-bootcamp  # TO COMPLETE: Match this label with the labels in your Deployment
  ports:
    - port: 8080  # TO COMPLETE: Specify the port that your service should expose
      targetPort: 8080  # TO COMPLETE: Specify the target port of your pods
