version: '3'
services:
  redis:
    image: redis
    volumes:
      - redis_data:/data  # Mount a volume to store Redis data
  web:
    # COMPLETE HERE
    build: .
    ports:
      - "5000:8080"
    environment:
      - REDIS_HOST=redis  # Use the service name as the host
      - REDIS_PORT=6379   # The default Redis port
    depends_on:
      - redis

volumes:
  redis_data:



