
  
name: CI

on: [push]

jobs:
 build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: project/backend

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'project/backend/package-lock.json'
    - run: npm ci
    - run: npm run build --if-present
    - name: Debug Information
      run: |
        echo "Current directory: $(pwd)"
        echo "Contents of project/backend: $(ls -al ${GITHUB_WORKSPACE}/project/backend)"
    - name: Check MySQL Service Status
      run: |
        sudo service mysql status
    - name: Print MySQL Error Log
      run: |
        cat /var/log/mysql/error.log
    - name: Set up MySQL
      run: |
        sudo service mysql start
        mysql -e 'CREATE DATABASE test;' -uroot -proot
        sleep 5  # Add a delay of 5 seconds
    - run: npm test