name: Node.js CI

on:
  push:
    branches: [ "main","dev-Alex" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: project/backend

    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      mysql:
        # Docker Hub image
        image: mysql:8.0
        env:
          MYSQL_DATABASE: test
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      matrix:
        node-version: ['18.x']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    steps:
    - name: Verify MySQL connection
      run: |
        mysql --version
        sudo apt-get install -y mysql-client
        mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -proot -e "SHOW DATABASES"
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'project/backend/package-lock.json'
    - run: npm ci
    - run: npm run build --if-present
    - name: Debug Information
      run: |
        echo "Current directory: $(pwd)"
        echo "Contents of project/backend: $(ls -al ${GITHUB_WORKSPACE}/project/backend)"

