name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  runs-on: ubuntu-20.04
  services:
    db:
      image: mysql:5.7
      ports:
        - 3306:3306
      env:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test
        MYSQL_USER: root
        MYSQL_PASSWORD: root
      options: >-
        --health-cmd "mysqladmin ping"
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5

  strategy:
    matrix:
      node-version: ['18.x']
      # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
  
  steps:
    - name: Show Docker containers
      run: docker ps -a
    - name: Show databases for root user
      run: mysql --protocol=tcp -h localhost -P 3306 -u root -proot -e "SHOW DATABASES"
    - name: Show databases for user1
      run: mysql --protocol=tcp -h localhost -P 3306 -u user1 -proot -e "SHOW DATABASES"
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'project/backend/package-lock.json'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

