# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

env:
  MYSQL_DATABASE: test
  MYSQL_USER: root
  MYSQL_PASSWORD: root
  MYSQL_HOST: mysql-master
  NODE_ENV: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: project/backend

    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      mysql:
        # Docker Hub image
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: ${{env.MYSQL_DATABASE}}
          MYSQL_ROOT_PASSWORD: ${{env.MYSQL_PASSWORD}}
        options: >-
          --name=mysql-master
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    strategy:
      matrix:
        node-version: ['18.x']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'project/backend/package-lock.json'
    - run: npm ci
    - run: npm run build --if-present
    - name: Debug Information
      run: |
        echo "Current directory: $(pwd)"
        echo "Contents of project/backend: $(ls -al ${GITHUB_WORKSPACE}/project/backend)"
        echo "MYSQL_PASSWORD: $MYSQL_PASSWORD"
        echo "MYSQL_DATABASE: $MYSQL_DATABASE"

    - name: Import Database Data
      run: mysql -h localhost -P 3306 -u root -p$MYSQL_PASSWORD $MYSQL_DATABASE < ${GITHUB_WORKSPACE}/project/backend/dumb.sql




    - run: npm test
